### ISSUE TITLE
Allow admins to set individual player power levels with /mf force (power) (player) (number)

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#410]
By having a generic Set Command, we will be able to easily extend it to allow admins to set other aspects of the plugin later.

**Comment by dmccoystephenson** [comment]
Assigned to myself to reserve this issue. Will assign to @TDL when he joins.

**Comment by dmccoystephenson** [comment]
Removed the next release label for now, just in case @TDL doesn't join in the next few days

**Comment by tdl** [comment]
probably you are mentioning the wrong person, I know nothing about this project :)

**Comment by dmccoystephenson** [comment]
Sorry about that Tom!
