### ISSUE TITLE
Fix players getting assigned an additional player power record upon restart, causing multiple messages with power-related messages that are sent to the player (v3.3)

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#473]
Seen with /mf power

Also seen with hourly power increase alert:
https://i.imgur.com/qV1im5m.png

**Comment by Pasarus** [comment]
Found the bug, UtilitySubsystem line 217
    public boolean hasPowerRecord(UUID playerUUID) {
        return main.playerPowerRecords.contains(playerUUID);
    }

**Comment by dmccoystephenson** [comment]
Nice!
