### ISSUE TITLE
Gates

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#585]
Add simple gates for castle walls to the plugin that disappear if the land they are on gets claimed.

**Comment by philbgarner** [comment]
- a designated gate selection tool
- a similar worldedit feature to select two blocks
- a way to save which blocks should go where
- a way to connect a lever or to the gate
- a way to move or temporarily delete blocks when the lever is activated
- to only allow gates in faction territory
- to remove gates when land is unclaimed/conquered
