### ISSUE TITLE
Create Command.java and have every command class inherit from it.

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#589]

**Comment by OpticFusion1** [comment]
Why not just use the command system spigot has?

**Comment by dmccoystephenson** [comment]
@OpticFusion1 
Every command is currently routed through Main.java in the onCommand() method. That method hands it off to the interpretCommand() method in the Command Subsystem. Depending on the label, it calls a method located in its respective command class. It's really just a way of organizing my code. 

Putting everything in Main.java wasn't working well, so I created things like CreateCommand.java, and then I didn't want all the command calls to be in Main.java, so I made CommandSubsystem.java.

I know it would be better to have each command class extend Listener and just define the listeners in Main.java, but nevertheless I would like to have this Command.java so I can abstract out the permission checking that is done in every command class currently. I think using inheritance I could made this code a lot more object-oriented.
