### ISSUE TITLE
/mf swearfealty "You haven't been offered vassalation by this faction!" sometimes when attempting to accept

### ISSUE THREAD

**Issue by philbgarner** [DansPlugins/Medieval-Factions#653]
Changing title of this issue since I've already created the branch with this issue number.  I could not reproduce.

**Comment by philbgarner** [comment]
Can't reproduce locally, not sure where the bug exists the code that starts that conditional block seems pretty solid.

**Comment by dmccoystephenson** [comment]
We need to verify that this is actually a problem. It may be due to an error with updating. I'll test more later today hopefully.
