### ISSUE TITLE
Players that Leave a Faction and Join Another Claim Chunks Under their Old Faction.

### ISSUE THREAD

**Issue by philbgarner** [DansPlugins/Medieval-Factions#657]
feedback #2 today
someone quit their faction and joined mine, but when they claim land it still appears as claimed by their previous faction
somehow they can claim land for their old faction, which also means they lose ability to interact with stuff they just claimed since they're in the new one

**Comment by dmccoystephenson** [comment]
I wonder if that player who joined the other faction was still considered an officer in his old faction.

**Comment by dmccoystephenson** [comment]
Closing this because I assumed fixing #683 fixed this.
