### ISSUE TITLE
Add a config option to disallow conquering if the chunks to the North, East, South and West of a targeted enemy chunk are claimed by the enemy faction.

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#670]
Let X = enemy target chunk
Let U = unclaimed chunk
Let E = enemy chunk
Let F = friendly chunk

**Unclaimable:**
U E U
E X E
U E U

Since X is surrounded by chunks claimed by the enemy faction, it is unclaimable.

**Claimable**
U E U
E X E
U **U** U

Since X has an unclaimed chunk to the south of it, it is claimable.

**Claimable**
F E E
F X E
F E E

Since X has a chunk that is not claimed by the same faction the west of it, it is claimable.

**More Generally**
Add a config option to disallow players from conquering an enemy claimed chunk if it is surrounded by enemy claimed chunks on all four adjacent sides.

**Comment by dmccoystephenson** [comment]
I would like for this to be added to the v3.5 update. It seems like it would be relatively simple to do.

**Comment by dmccoystephenson** [comment]
I ran into some problems trying to implement this and my branch "border-claiming-only" became pretty messy. I closed the pull request I had open for this, #716.

I will likely create a new branch and just try this again, but if anyone else wants to take a shot on "border-claiming-only" or a new branch go ahead.

**Comment by LukaPix** [comment]
what about.. just checking if a wilderness chunk is adjacent ?

**Comment by dmccoystephenson** [comment]
> what about.. just checking if a wilderness chunk is adjacent ?
> If no = can't claim.
> Would have some sideffect in various cases but all not game breaking

That sounds good to me, @LukaPix
