### ISSUE TITLE
Possible Bug: Power Does Not Seem to be Increasing

### ISSUE THREAD

**Issue by philbgarner** [DansPlugins/Medieval-Factions#673]
Note1765 said he got a 2 power increase at around 1:20am EST, Retro and I haven't received it.  Wondered if something might be going wrong there?  Very strange.

**Comment by dmccoystephenson** [comment]
We should make sure the scheduled power increases work before we upload v3.5 to SpigotMC.

**Comment by philbgarner** [comment]
I suspect this is caused by a comparison done inside the schedule power increase method on UtilitySubsystem.java:

if (powerRecord.getPowerLevel() < powerRecord.maxPower()) {
