### ISSUE TITLE
Fix players not getting removed from officer list when they leave a faction.

### ISSUE THREAD

**Issue by philbgarner** [DansPlugins/Medieval-Factions#683]

**Comment by dmccoystephenson** [comment]
This is likely the cause of #657 as well.
https://github.com/dansplugins/medieval-factions/issues/657

**Comment by dmccoystephenson** [comment]
The block of code that executes when a non-owner leaves their faction doesn't remove their officer status.
https://github.com/DansPlugins/Medieval-Factions/blob/7cf18fe5db62dedcd86bbd5d9b5396595cc5c084/src/main/java/factionsystem/Commands/LeaveCommand.java#L84

**Comment by dmccoystephenson** [comment]
The block of code that executes when a non-owner leaves their faction doesn't remove their officer status.
https://github.com/DansPlugins/Medieval-Factions/blob/7cf18fe5db62dedcd86bbd5d9b5396595cc5c084/src/main/java/factionsystem/Commands/LeaveCommand.java#L84
