### ISSUE TITLE
Vassal Power Contribution

### ISSUE THREAD

**Issue by philbgarner** [DansPlugins/Medieval-Factions#684]
**Variables**
Let A = (cumulative max power level of liege faction)
Let B = (cumulative power level of liege faction without vassal contribution)
Let C = (cumulative power level of vassal factions)

Let X = vassalPowerContributionPercentage config option (a double)

Let D = (cumulative power level of liege faction with vassal contribution)

**Formula**
When ( B > ( A / 2 ) ) ,

( D = B + ( C * X ) )

**Example 1**
A = cumulative max power level of the liege faction = 100
B = cumulative power level of the liege faction without vassal contribution = 60
C = cumulative power level of the vassal faction = 40

X = 0.20          (20%)

D = cumulative power level of the liege faction with vassal contribution = ( 60 + (40 * 0.20) ) = ( 60 + 8 ) = 68

**Example 2**
A = cumulative max power level of the liege faction = 100
B = cumulative power level of the liege faction without vassal contribution = 40
C = cumulative power level of the vassal faction = 40

X = 0.20          (20%)

Since ( 40 < ( 100 / 2 ) ) ,

D = B = 40

**Comment by dmccoystephenson** [comment]
We may need to talk about this one more to ensure that lieges don't become overpowered. It probably won't be in v3.5.

**Comment by dmccoystephenson** [comment]
Were we to not include this in v3.5, however, we would need to include methods to update cumulative powers of existing liege/vassal relationships.

**Comment by dmccoystephenson** [comment]
I have updated the title and description of this issue.

With the new defined system, liege factions will enjoy a boost to their power so long as they retain 50% of their max power without vassal contributions. This will make it so that if a faction's power is low enough, vassal contributions won't apply and it will still be possible to claim all land that a liege faction possesses.
